name: "Disapprove Pull Request"
description: "Disapprove a pull request"

author: "Atolycs"

branding:
  icon: git-pull-request
  color: red

inputs:
  token:
    description: "Github token"
    required: true
    default: ${{ github.token }}

  message:
    description: "Message to disapprove"
    required: false
    default: "This pull request is not approved"

runs:
  using: "node20"
  main: "dist/index.cjs"